import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import butterdots from '../public/butterdots.jpg'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Butter Dots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Butter Dots Dot Com</h3>
        <p className={styles.description}>(try saying it out loud...fun!)</p>
        <p className={styles.description}>(yes, Jon, I fixed the typo)</p>
        <div className={styles.card}>
          {' '}
          <Image
            src="/butterdots.jpg"
            alt="butter dots in a metal bowl with ice"
            height={700}
            width={700}
          />
        </div>
        <div className={styles.description}>
          Butter Dots are small discs of butter (european style works best)
          which are formed in ice cold water by rolling bits of butter into a
          ball and then pressing them flat.
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
